=== pablomagnaghi/7552-tp/TpTaller2V2/Doc/XMLSchema/composicion.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	
	<xsd:element name="diagrama" type="tipo_diagrama" />

	<xsd:complexType name="tipo_diagrama">
		<xsd:sequence>
			<xsd:element name="diagrama_ancestro" type="xsd:string" minOccurs="0" />
			<xsd:element name="diagrama_hijo" type="xsd:string" minOccurs="0" maxOccurs="unbounded" />
			<xsd:element name="entidad_nueva" type="tipo_entidad_nueva" minOccurs="0" maxOccurs="unbounded" />
			<xsd:element name="entidad_global" type="tipo_entidad_global" minOccurs="0" maxOccurs="unbounded" />
			<xsd:element name="relacion" type="tipo_relacion" minOccurs="0" maxOccurs="unbounded" />
			<xsd:element name="jerarquia" type="tipo_jerarquia" minOccurs="0" maxOccurs="unbounded" />
		</xsd:sequence>
		<xsd:attribute name="nombre" type="xsd:string" use="required" />
	</xsd:complexType>


	<xsd:complexType name="tipo_componente" abstract="true">
		<xsd:attribute name="codigo" type="xsd:integer" use="required" />
		<xsd:attribute name="nombre" type="xsd:string" />
	</xsd:complexType> 

	
	<xsd:complexType name="tipo_entidad_nueva">
		<xsd:complexContent>
			<xsd:extension base="tipo_componente">
				<xsd:sequence>
					<xsd:element name="atributo" type="tipo_atributo" minOccurs="1" maxOccurs="unbounded" />
					<xsd:element name="identificador" type="tipo_identificador" minOccurs="1" maxOccurs="unbounded" />
					<xsd:element name="relacion" type="xsd:integer" minOccurs="0" maxOccurs="unbounded" /> 
					<xsd:element name="jerarquia" type="xsd:integer" minOccurs="0" maxOccurs="unbounded" />
				</xsd:sequence>
				<xsd:attribute name="tipo" type="tipo_tipo_entidad" />
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
	
	<xsd:complexType name="tipo_entidad_global">
		<xsd:complexContent>
			<xsd:extension base="tipo_componente">
				<xsd:attribute name="diagrama_ancestro" type="xsd:string" use="required" />
				<xsd:attribute name="codigo_diagrama_ancestro" type="xsd:integer" use="required" />
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
	
	<xsd:simpleType name="tipo_tipo_entidad">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="cosa" />
			<xsd:enumeration value="dominio" />
			<xsd:enumeration value="historica" />
			<xsd:enumeration value="programada" />
		</xsd:restriction>
	</xsd:simpleType>

	
	<xsd:complexType name="tipo_atributo">
		<xsd:complexContent>
			<xsd:extension base="tipo_componente">
				<xsd:sequence>
					<xsd:element name="atributo" type="tipo_atributo" minOccurs="0" maxOccurs="unbounded" />
				</xsd:sequence>
				<xsd:attribute name="tipo" type="tipo_tipo_atributo" use="required" /> 
				<xsd:attribute name="cardinalidad_minima" type="xsd:string" />
				<xsd:attribute name="cardinalidad_maxima" type="xsd:string" />
				<xsd:attribute name="expresion" type="xsd:string" />
			</xsd:extension>
		</xsd:complexContent>					
	</xsd:complexType>
	
	<xsd:simpleType name="tipo_tipo_atributo">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="caracterizacion" />
			<xsd:enumeration value="copiado" />
			<xsd:enumeration value="calculado" />
		</xsd:restriction>
	</xsd:simpleType>
	

	<xsd:complexType name="tipo_identificador">
		<xsd:sequence>
			<xsd:element name="atributo" type="xsd:integer" minOccurs="1" maxOccurs="unbounded" />
			<xsd:element name="relacion" type="xsd:integer" minOccurs="0" maxOccurs="unbounded" /> 
		</xsd:sequence>
	</xsd:complexType>
	
	
	<xsd:complexType name="tipo_relacion">
		<xsd:complexContent>
			<xsd:extension base="tipo_componente">
				<xsd:sequence>
					<xsd:element name="entidad" type="tipo_entidad_cardinalidad" minOccurs="2" maxOccurs="unbounded" />
					<xsd:element name="atributo" type="tipo_atributo" minOccurs="0" maxOccurs="unbounded" />
				</xsd:sequence>
				<xsd:attribute name="tipo" type="tipo_tipo_relacion" />
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
	
	<xsd:complexType name="tipo_entidad_cardinalidad">
		<xsd:attribute name="codigo" type="xsd:integer" use="required" />
		<xsd:attribute name="cardinalidad_minima" type="xsd:string" />
		<xsd:attribute name="cardinalidad_maxima" type="xsd:string" />
		<xsd:attribute name="rol" type="xsd:string" />
	</xsd:complexType>
	
	<xsd:simpleType name="tipo_tipo_relacion">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="asociacion" />
			<xsd:enumeration value="composicion" />
		</xsd:restriction>
	</xsd:simpleType>
	

	<xsd:complexType name="tipo_jerarquia">
		<xsd:complexContent>
			<xsd:extension base="tipo_componente">
				<xsd:sequence>
					<xsd:element name="entidad_general" type="xsd:integer" />
					<xsd:element name="entidad_especializada" type="xsd:integer" maxOccurs="unbounded" />
				</xsd:sequence>
				<xsd:attribute name="cobertura" type="tipo_cobertura" />
				<xsd:attribute name="interseccion" type="tipo_interseccion" />
			</xsd:extension>
		</xsd:complexContent>	
	</xsd:complexType>
	
	<xsd:simpleType name="tipo_cobertura">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="total" />
			<xsd:enumeration value="parcial" />
		</xsd:restriction>
	</xsd:simpleType>
	
	<xsd:simpleType name="tipo_interseccion">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="exclusiva" />
			<xsd:enumeration value="superpuesta" />
		</xsd:restriction>
	</xsd:simpleType>
	
</xsd:schema>

=== pablomagnaghi/7552-tp/Tp Taller 2/Doc/XMLSchema/boleteria_teatro-comp.xml
<?xml version="1.0" encoding="UTF-8"?>
<diagrama xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:noNamespaceSchemaLocation="composicion.xsd"
	nombre="boleteria teatro">
		
	<entidad nombre="SeccionSala">
		<atributo nombre="nroSecc" tipo="integer"/>
		<atributo nombre="nomSecc" tipo="string"/>
		<identificador>
			<atributo>nroSecc</atributo>
		</identificador>
		<identificador>
			<atributo>nomSecc</atributo>
		</identificador>
		<relacion>SL</relacion>
	</entidad>
	
	<entidad nombre="Localidad">
		<atributo nombre="fila" tipo="integer" />
		<atributo nombre="nroButaca" tipo="integer" />
		<identificador>
			<atributo>fila</atributo>
			<atributo>nroButaca</atributo>
			<relacion>SL</relacion>
		</identificador>
		<relacion>SL</relacion>
		<relacion>VtaLoc</relacion>
	</entidad>
	
	<entidad nombre="Obra">
		<atributo nombre="idObra" tipo="integer" />
		<atributo nombre="titulo" tipo="string" />
		<atributo nombre="autor" tipo="string" cardinalidad="(1,n)" />
		<atributo nombre="director" tipo="string" cardinalidad="(1,n)" />
		<atributo nombre="genero" tipo="string" />
		<atributo nombre="nroProxFunc" tipo="integer" />
		<identificador>
			<atributo>idObra</atributo>
		</identificador>
		<identificador>
			<atributo>titulo</atributo>
		</identificador>  
		<relacion>VtaLoc</relacion>
		<relacion>FO</relacion>
	</entidad>
	
	<entidad nombre="Funcion">
		<atributo nombre="nroFunc" tipo="integer" />
		<atributo nombre="fecha" tipo="date" />
		<atributo nombre="hora" tipo="date" />
		<identificador>
			<atributo>nroFunc</atributo>
			<relacion>FO</relacion>
		</identificador>
		<identificador>
			<atributo>fecha</atributo>
			<atributo>hora</atributo>
			<relacion>FO</relacion>
		</identificador>
		<relacion>FO</relacion> 
	</entidad>
	
	<relacion nombre="SL">
		<entidad nombre="SeccionSala" cardinalidad="(1,n)" />
		<entidad nombre="Localidad" cardinalidad="(1,1)" />
	</relacion>
	
	<relacion nombre="VtaLoc">
		<entidad nombre="Localidad" cardinalidad="(0,n)" />
		<entidad nombre="Obra" cardinalidad="(0,n)" />
		<atributo nombre="tarj" tipo="complex" cardinalidad="(0,1)">
			<atributo_hijo nombre="nomTarj" tipo="string" />
			<atributo_hijo nombre="bco" tipo="integer" />
			<atributo_hijo nombre="nroTarj" tipo="integer" />
			<atributo_hijo nombre="nroAutoriz" tipo="integer" />
			<atributo_hijo nombre="cr" tipo="complex" cardinalidad="(0,1)">
				<atributo_hijo nombre="cuotas" tipo="integer" />
				<atributo_hijo nombre="int" tipo="integer" cardinalidad="(0,1)"/>
			</atributo_hijo>
		</atributo>
	</relacion>
	
	<relacion nombre="FO">
		<entidad nombre="Obra" cardinalidad="(0,n)"/>
		<entidad nombre="Funcion" cardinalidad="(1,1)" />
	</relacion>
	
</diagrama>
