=== pablomagnaghi/7552-tp/TpTaller2V2/Doc/XMLSchema/composicion.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	
	<xsd:element name="diagrama" type="tipo_diagrama" />

	<xsd:complexType name="tipo_diagrama">
		<xsd:sequence>
			<xsd:element name="diagrama_ancestro" type="xsd:string" minOccurs="0" />
			<xsd:element name="diagrama_hijo" type="xsd:string" minOccurs="0" maxOccurs="unbounded" />
			<xsd:element name="entidad_nueva" type="tipo_entidad_nueva" minOccurs="0" maxOccurs="unbounded" />
			<xsd:element name="entidad_global" type="tipo_entidad_global" minOccurs="0" maxOccurs="unbounded" />
			<xsd:element name="relacion" type="tipo_relacion" minOccurs="0" maxOccurs="unbounded" />
			<xsd:element name="jerarquia" type="tipo_jerarquia" minOccurs="0" maxOccurs="unbounded" />
		</xsd:sequence>
		<xsd:attribute name="nombre" type="xsd:string" use="required" />
	</xsd:complexType>


	<xsd:complexType name="tipo_componente" abstract="true">
		<xsd:attribute name="codigo" type="xsd:integer" use="required" />
		<xsd:attribute name="nombre" type="xsd:string" />
	</xsd:complexType> 

	
	<xsd:complexType name="tipo_entidad_nueva">
		<xsd:complexContent>
			<xsd:extension base="tipo_componente">
				<xsd:sequence>
					<xsd:element name="atributo" type="tipo_atributo" minOccurs="1" maxOccurs="unbounded" />
					<xsd:element name="identificador" type="tipo_identificador" minOccurs="1" maxOccurs="unbounded" />
					<xsd:element name="relacion" type="xsd:integer" minOccurs="0" maxOccurs="unbounded" /> 
					<xsd:element name="jerarquia" type="xsd:integer" minOccurs="0" maxOccurs="unbounded" />
				</xsd:sequence>
				<xsd:attribute name="tipo" type="tipo_tipo_entidad" />
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
	
	<xsd:complexType name="tipo_entidad_global">
		<xsd:complexContent>
			<xsd:extension base="tipo_componente">
				<xsd:attribute name="diagrama_ancestro" type="xsd:string" use="required" />
				<xsd:attribute name="codigo_diagrama_ancestro" type="xsd:integer" use="required" />
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
	
	<xsd:simpleType name="tipo_tipo_entidad">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="cosa" />
			<xsd:enumeration value="dominio" />
			<xsd:enumeration value="historica" />
			<xsd:enumeration value="programada" />
		</xsd:restriction>
	</xsd:simpleType>

	
	<xsd:complexType name="tipo_atributo">
		<xsd:complexContent>
			<xsd:extension base="tipo_componente">
				<xsd:sequence>
					<xsd:element name="atributo" type="tipo_atributo" minOccurs="0" maxOccurs="unbounded" />
				</xsd:sequence>
				<xsd:attribute name="tipo" type="tipo_tipo_atributo" use="required" /> 
				<xsd:attribute name="cardinalidad_minima" type="xsd:string" />
				<xsd:attribute name="cardinalidad_maxima" type="xsd:string" />
				<xsd:attribute name="expresion" type="xsd:string" />
			</xsd:extension>
		</xsd:complexContent>					
	</xsd:complexType>
	
	<xsd:simpleType name="tipo_tipo_atributo">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="caracterizacion" />
			<xsd:enumeration value="copiado" />
			<xsd:enumeration value="calculado" />
		</xsd:restriction>
	</xsd:simpleType>
	

	<xsd:complexType name="tipo_identificador">
		<xsd:sequence>
			<xsd:element name="atributo" type="xsd:integer" minOccurs="1" maxOccurs="unbounded" />
			<xsd:element name="relacion" type="xsd:integer" minOccurs="0" maxOccurs="unbounded" /> 
		</xsd:sequence>
	</xsd:complexType>
	
	
	<xsd:complexType name="tipo_relacion">
		<xsd:complexContent>
			<xsd:extension base="tipo_componente">
				<xsd:sequence>
					<xsd:element name="entidad" type="tipo_entidad_cardinalidad" minOccurs="2" maxOccurs="unbounded" />
					<xsd:element name="atributo" type="tipo_atributo" minOccurs="0" maxOccurs="unbounded" />
				</xsd:sequence>
				<xsd:attribute name="tipo" type="tipo_tipo_relacion" />
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
	
	<xsd:complexType name="tipo_entidad_cardinalidad">
		<xsd:attribute name="codigo" type="xsd:integer" use="required" />
		<xsd:attribute name="cardinalidad_minima" type="xsd:string" />
		<xsd:attribute name="cardinalidad_maxima" type="xsd:string" />
		<xsd:attribute name="rol" type="xsd:string" />
	</xsd:complexType>
	
	<xsd:simpleType name="tipo_tipo_relacion">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="asociacion" />
			<xsd:enumeration value="composicion" />
		</xsd:restriction>
	</xsd:simpleType>
	

	<xsd:complexType name="tipo_jerarquia">
		<xsd:complexContent>
			<xsd:extension base="tipo_componente">
				<xsd:sequence>
					<xsd:element name="entidad_general" type="xsd:integer" />
					<xsd:element name="entidad_especializada" type="xsd:integer" maxOccurs="unbounded" />
				</xsd:sequence>
				<xsd:attribute name="cobertura" type="tipo_cobertura" />
				<xsd:attribute name="interseccion" type="tipo_interseccion" />
			</xsd:extension>
		</xsd:complexContent>	
	</xsd:complexType>
	
	<xsd:simpleType name="tipo_cobertura">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="total" />
			<xsd:enumeration value="parcial" />
		</xsd:restriction>
	</xsd:simpleType>
	
	<xsd:simpleType name="tipo_interseccion">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="exclusiva" />
			<xsd:enumeration value="superpuesta" />
		</xsd:restriction>
	</xsd:simpleType>
	
</xsd:schema>

=== pablomagnaghi/7552-tp/trunk/TpTaller2V2/proyectos/proyecto2/Principal-COMP.xml
<?xml version="1.0" encoding="UTF-8"?>
<diagrama xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="composicion.xsd" nombre="Principal"><entidad_nueva codigo="1" nombre="Entidad 1" tipo=""><atributo codigo="2" nombre="Atributo 1" tipo="" cardinalidad_minima="1" cardinalidad_maxima="*"><atributo codigo="5" nombre="Atributo 1_1" tipo="" cardinalidad_minima="1" cardinalidad_maxima="2"/></atributo></entidad_nueva><entidad_nueva codigo="10" nombre="Entidad 2" tipo=""><atributo codigo="11" nombre="Atributo 2" tipo="" cardinalidad_minima="1" cardinalidad_maxima="1"/></entidad_nueva><entidad_nueva codigo="24" nombre="Entidad 3" tipo=""/><entidad_nueva codigo="25" nombre="Entidad 4" tipo=""/><entidad_nueva codigo="27" nombre="Entidad 5" tipo=""/><relacion codigo="13" nombre="Relacion 1"><union_entidad_relacion  codigo="14" nombre="Union" entidad="1" cardinalidad_minima="1" cardinalidad_maxima="*"/><union_entidad_relacion  codigo="15" nombre="Union" entidad="10" cardinalidad_minima="1" cardinalidad_maxima="N"/><atributo codigo="16" nombre="Atributo R1" tipo="" cardinalidad_minima="1" cardinalidad_maxima="1"><atributo codigo="18" nombre="Atributo R1_1" tipo="" cardinalidad_minima="1" cardinalidad_maxima="1"/></atributo></relacion><jerarquia codigo="28" nombre="j2" cobertura="" interseccion=""><entidad_general>25</entidad_general><entidad_especializada>27</entidad_especializada></jerarquia></diagrama>

=== pablomagnaghi/7552-tp/trunk/TpTaller2V2/proyectos/PromoHiper/Principal-COMP.xml
<?xml version="1.0" encoding="UTF-8"?>
<diagrama xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="composicion.xsd" nombre="Principal" estado="sin_validar"><entidad_nueva codigo="1" nombre="TipoProd" tipo="cosa"><atributo codigo="2" nombre="ct" tipo="Caracterizacion" cardinalidad_minima="1" cardinalidad_maxima="1"/><atributo codigo="4" nombre="dt" tipo="Caracterizacion" cardinalidad_minima="1" cardinalidad_maxima="1"/><identificador><atributo>2</atributo></identificador></entidad_nueva><entidad_nueva codigo="6" nombre="SubTipoProd" tipo="cosa"><atributo codigo="7" nombre="dst" tipo="Caracterizacion" cardinalidad_minima="1" cardinalidad_maxima="1"/><atributo codigo="9" nombre="cst" tipo="Caracterizacion" cardinalidad_minima="1" cardinalidad_maxima="1"/><identificador><atributo>9</atributo><relacion>11</relacion></identificador></entidad_nueva><entidad_nueva codigo="14" nombre="Producto" tipo="cosa"><atributo codigo="15" nombre="precio" tipo="Caracterizacion" cardinalidad_minima="1" cardinalidad_maxima="1"/><atributo codigo="17" nombre="presentacion" tipo="Caracterizacion" cardinalidad_minima="1" cardinalidad_maxima="1"/><atributo codigo="19" nombre="nombre" tipo="Caracterizacion" cardinalidad_minima="1" cardinalidad_maxima="1"/><atributo codigo="21" nombre="codigo" tipo="Caracterizacion" cardinalidad_minima="1" cardinalidad_maxima="1"/><identificador><atributo>21</atributo><relacion>23</relacion></identificador><identificador><atributo>21</atributo><relacion>31</relacion></identificador></entidad_nueva><entidad_nueva codigo="26" nombre="Marca" tipo="cosa"><atributo codigo="27" nombre="nombre" tipo="Caracterizacion" cardinalidad_minima="1" cardinalidad_maxima="1"/><atributo codigo="29" nombre="codM" tipo="Caracterizacion" cardinalidad_minima="1" cardinalidad_maxima="1"/><identificador><atributo>29</atributo></identificador></entidad_nueva><entidad_nueva codigo="1" nombre="Beneficio" tipo="cosa"><atributo codigo="2" nombre="dias" tipo="Caracterizacion" cardinalidad_minima="1" cardinalidad_maxima="1"/><atributo codigo="4" nombre="desde" tipo="Caracterizacion" cardinalidad_minima="1" cardinalidad_maxima="1"/><atributo codigo="6" nombre="hasta" tipo="Caracterizacion" cardinalidad_minima="1" cardinalidad_maxima="1"/></entidad_nueva><relacion codigo="11" nombre="TP/STP" tipo="asociacion"><union_entidad_relacion  codigo="12" nombre="Union" entidad="1" cardinalidad_minima="0" cardinalidad_maxima="n"/><union_entidad_relacion  codigo="13" nombre="Union" entidad="6" cardinalidad_minima="1" cardinalidad_maxima=""/></relacion><relacion codigo="23" nombre="STP/P" tipo="asociacion"><union_entidad_relacion  codigo="24" nombre="Union" entidad="6" cardinalidad_minima="1" cardinalidad_maxima="n"/><union_entidad_relacion  codigo="25" nombre="Union" entidad="14" cardinalidad_minima="1" cardinalidad_maxima=""/></relacion><relacion codigo="31" nombre="M/P" tipo="asociacion"><union_entidad_relacion  codigo="32" nombre="Union" entidad="14" cardinalidad_minima="1" cardinalidad_maxima=""/><union_entidad_relacion  codigo="33" nombre="Union" entidad="26" cardinalidad_minima="1" cardinalidad_maxima="n"/></relacion></diagrama>

=== pablomagnaghi/7552-tp/TpTaller2V2/Prueba3-EjemploCreacion.xml
<?xml version="1.0" encoding="UTF-8"?>
<diagrama xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="composicion.xsd" nombre="Principal"><entidad_nueva codigo="1" nombre="EntidadA" tipo="cosa"><atributo codigo="2" nombre="atributoA" tipo="caracterizacion"/><identificador><atributo>2</atributo><relacion>5</relacion></identificador><relacion>5</relacion></entidad_nueva><entidad_nueva codigo="3" nombre="entidadB" tipo="cosa"><atributo codigo="4" nombre="atributoB" tipo="caracterizacion"/><identificador><atributo>4</atributo></identificador><relacion>5</relacion></entidad_nueva><relacion codigo="5" nombre="Relacion" tipo="asociacion"><entidad_relacion entidad="1" cardinalidad_minima="1" cardinalidad_maxima="n"/><entidad_relacion entidad="3" cardinalidad_minima="1" cardinalidad_maxima="1"/></relacion></diagrama>

=== pablomagnaghi/7552-tp/TPtaller2/proyectos/test4/DiagramaHijo-COMP.xml
<?xml version="1.0" encoding="UTF-8"?>
<diagrama xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="composicion.xsd" nombre="DiagramaHijo" estado="sin_validar"><diagrama_ancestro>Principal</diagrama_ancestro><entidad_nueva codigo="3" nombre="Entidad 2" tipo=""/><entidad_nueva codigo="6" nombre="Entidad 3" tipo=""/><entidad_nueva codigo="1" nombre="Entidad 4" tipo=""/><entidad_global codigo="2" nombre="Entidad Padre" diagrama_ancestro="Principal" codigo_entidad_nueva="1"/><relacion codigo="5" nombre="Relacion"><union_entidad_relacion  codigo="7" nombre="Union" entidad="2" cardinalidad_minima="" cardinalidad_maxima=""/><union_entidad_relacion  codigo="8" nombre="Union" entidad="6" cardinalidad_minima="" cardinalidad_maxima=""/></relacion><jerarquia codigo="4" nombre="j1" cobertura="parcial" interseccion="exclusiva"><entidad_general>2</entidad_general><entidad_especializada>3</entidad_especializada><entidad_especializada>1</entidad_especializada></jerarquia></diagrama>

=== pablomagnaghi/7552-tp/trunk/TpTaller2V2/PruebaCarga2-DiagramaPrincipal.xml
<?xml version="1.0" encoding="UTF-8"?>
<diagrama xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="composicion.xsd" nombre="Principal"><entidad_nueva codigo="1" nombre="EntidadNuevaPapa" tipo="cosa"><atributo codigo="2" nombre="idPapa" tipo="caracterizacion"/><identificador><atributo>2</atributo></identificador><jerarquia>7</jerarquia></entidad_nueva><entidad_nueva codigo="3" nombre="EntidadNuevaA" tipo="cosa"><atributo codigo="4" nombre="idA" tipo="caracterizacion"/><identificador><atributo>4</atributo></identificador><jerarquia>7</jerarquia></entidad_nueva><entidad_nueva codigo="5" nombre="entidadNuevaB" tipo="cosa"><atributo codigo="6" nombre="idB" tipo="caracterizacion"/><identificador><atributo>6</atributo></identificador><jerarquia>7</jerarquia></entidad_nueva><jerarquia codigo="7" cobertura="total" interseccion="exclusiva"><entidad_general>1</entidad_general><entidad_especializada>3</entidad_especializada><entidad_especializada>5</entidad_especializada></jerarquia></diagrama>

=== pablomagnaghi/7552-tp/TpTaller2V2/PruebaDeCarga.xml
<?xml version="1.0" encoding="UTF-8"?>
<diagrama xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="composicion.xsd" nombre="Principal"><entidad_nueva codigo="1" nombre="SeccionSala" tipo="cosa"><atributo codigo="2" nombre="nroSecc" tipo="caracterizacion"/><atributo codigo="3" nombre="nomSecc" tipo="caracterizacion"/><identificador><atributo>2</atributo></identificador><identificador><atributo>3</atributo></identificador></entidad_nueva><entidad_nueva codigo="4" nombre="Localidad" tipo="cosa"><atributo codigo="5" nombre="fila" tipo="caracterizacion"/><atributo codigo="6" nombre="nroButaca" tipo="caracterizacion"/><identificador><atributo>5</atributo><atributo>6</atributo></identificador><identificador><atributo>6</atributo></identificador></entidad_nueva><entidad_nueva codigo="7" nombre="Obra" tipo="cosa"><atributo codigo="8" nombre="idObra" tipo="caracterizacion"/><atributo codigo="9" nombre="titulo" tipo="caracterizacion"/><atributo codigo="10" nombre="autor" tipo="caracterizacion" cardinalidad_minima="1" cardinalidad_maxima="n"/><atributo codigo="11" nombre="director" tipo="caracterizacion" cardinalidad_minima="1" cardinalidad_maxima="n"/><atributo codigo="12" nombre="genero" tipo="caracterizacion"/><atributo codigo="13" nombre="nroProxFunc" tipo="caracterizacion"/><identificador><atributo>8</atributo></identificador><identificador><atributo>9</atributo></identificador></entidad_nueva><entidad_nueva codigo="14" nombre="Funcion" tipo="cosa"><atributo codigo="15" nombre="nroFunc" tipo="caracterizacion"/><atributo codigo="16" nombre="fecha" tipo="caracterizacion"/><atributo codigo="17" nombre="hora" tipo="caracterizacion"/><identificador><atributo>15</atributo></identificador><identificador><atributo>16</atributo><atributo>17</atributo></identificador></entidad_nueva></diagrama>

=== pablomagnaghi/7552-tp/trunk/TPtaller2/proyectos/proyecto1/Principal-COMP.xml
<?xml version="1.0" encoding="UTF-8"?>
<diagrama xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="composicion.xsd" nombre="Principal"><entidad_nueva codigo="1" nombre="Entidad 1" tipo=""><atributo codigo="11" nombre="Atributo 1" tipo="Copiado" cardinalidad_minima="1" cardinalidad_maxima="1"/><atributo codigo="13" nombre="Atributo 2" tipo="" cardinalidad_minima="1" cardinalidad_maxima="1"/><identificador><atributo>11</atributo></identificador></entidad_nueva><entidad_nueva codigo="2" nombre="Entidad 2" tipo=""><atributo codigo="27" nombre="Atributo 1A" tipo="" cardinalidad_minima="1" cardinalidad_maxima="1"/><identificador><atributo>27</atributo><relacion>3</relacion></identificador></entidad_nueva><entidad_nueva codigo="6" nombre="Entidad 3" tipo=""/><entidad_nueva codigo="8" nombre="Entidad 4" tipo=""><atributo codigo="21" nombre="Atributo 4" tipo="" cardinalidad_minima="1" cardinalidad_maxima="1"><atributo codigo="23" nombre="Atributo 4 4" tipo="" cardinalidad_minima="1" cardinalidad_maxima="1"/><atributo codigo="25" nombre="Atributo 4 1" tipo="" cardinalidad_minima="1" cardinalidad_maxima="1"/></atributo><identificador><atributo>21</atributo></identificador></entidad_nueva><entidad_nueva codigo="9" nombre="Entidad 5" tipo=""><atributo codigo="15" nombre="Atributo 1" tipo="" cardinalidad_minima="1" cardinalidad_maxima="1"><atributo codigo="17" nombre="Atributo 1:1" tipo="" expresion="ewga" cardinalidad_minima="1" cardinalidad_maxima="1"/></atributo><atributo codigo="19" nombre="Atributo 4" tipo="" cardinalidad_minima="1" cardinalidad_maxima="1"/><identificador><atributo>15</atributo><atributo>19</atributo></identificador></entidad_nueva><relacion codigo="3" nombre="Relacion 1"><union_entidad_relacion  codigo="4" nombre="Union" entidad="1" cardinalidad_minima="" cardinalidad_maxima=""/><union_entidad_relacion  codigo="5" nombre="Union" entidad="2" cardinalidad_minima="" cardinalidad_maxima=""/></relacion><jerarquia codigo="7" nombre="J1" cobertura="parcial" interseccion="exclusiva"><entidad_general>1</entidad_general><entidad_especializada>6</entidad_especializada></jerarquia><jerarquia codigo="10" nombre="J2" cobertura="total" interseccion="exclusiva"><entidad_general>6</entidad_general><entidad_especializada>8</entidad_especializada><entidad_especializada>9</entidad_especializada></jerarquia></diagrama>

=== pablomagnaghi/7552-tp/TpTaller2V2/proyectos/proyecto1/Principal-COMP.xml
<?xml version="1.0" encoding="UTF-8"?>
<diagrama xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="composicion.xsd" nombre="Principal"><entidad_nueva codigo="1" nombre="Entidad 1" tipo=""/><entidad_nueva codigo="2" nombre="Entidad 2" tipo=""/><entidad_nueva codigo="3" nombre="Entidad 3" tipo=""/><jerarquia codigo="4" nombre="JERARQUIA" cobertura="" interseccion=""><entidad_general>1</entidad_general><entidad_especializada>2</entidad_especializada><entidad_especializada>2</entidad_especializada><entidad_especializada>3</entidad_especializada><entidad_especializada>3</entidad_especializada></jerarquia></diagrama>
