=== pablomagnaghi/7552-tp/TpTaller2V2/Doc/XMLSchema/representacion.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

	<xsd:element name="diagrama" type="tipo_diagrama" />

	<xsd:complexType name="tipo_diagrama">
		<xsd:sequence>
			<xsd:element name="componente" type="tipo_componente" maxOccurs="unbounded" />
		</xsd:sequence>
		<xsd:attribute name="estado" type="tipo_estado_validacion" />
	</xsd:complexType>
	
	<xsd:simpleType name="tipo_estado_validacion">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="sin_validar" />
			<xsd:enumeration value="validado_con_observaciones" />
			<xsd:enumeration value="validado" />
		</xsd:restriction>
	</xsd:simpleType>
	
	<xsd:complexType name="tipo_componente">
		<xsd:sequence>
			<xsd:element name="posicion" type="tipo_posicion" />
			<xsd:element name="tamanio" type="tipo_tamanio" />
			<xsd:element name="color" type="xsd:string" />
		</xsd:sequence>
		<xsd:attribute name="codigo" type="xsd:integer" use="required" />
	</xsd:complexType>
	
	<xsd:complexType name="tipo_posicion">
		<xsd:attribute name="x" type="xsd:integer" use="required" />
		<xsd:attribute name="y" type="xsd:integer" use="required" />
	</xsd:complexType>

	<xsd:complexType name="tipo_tamanio">
		<xsd:attribute name="ancho" type="xsd:integer" use="required" />
		<xsd:attribute name="alto" type="xsd:integer" use="required" />
	</xsd:complexType>
	
</xsd:schema>

=== pablomagnaghi/7552-tp/trunk/Tp Taller 2/Doc/XMLSchema/boleteria_teatro-rep.xml
<?xml version="1.0" encoding="UTF-8"?>
<diagrama xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:noNamespaceSchemaLocation="representacion.xsd"
	estado="sin_validar">

	<componente codigo="1">
		<posicion x="10" y="10" />
		<tamanio ancho="20" alto="10" />
		<color>negro</color>
	</componente>	
	
	<componente codigo="2">
		<posicion x="9" y="9" />
		<tamanio ancho="5" alto="2" />
		<color>negro</color>
	</componente>	
	
	<componente codigo="3">
		<posicion x="11" y="9" />
		<tamanio ancho="5" alto="2" />
		<color>negro</color>
	</componente>	
	
</diagrama>
