=== pablomagnaghi/7552-tp/trunk/Tp Taller 2/Doc/XMLSchema/composicion.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	
	<xsd:element name="diagrama" type="tipo_diagrama" />

	<xsd:complexType name="tipo_diagrama">
		<xsd:sequence>
			<xsd:element name="diagrama_padre" type="xsd:string" minOccurs="0" />
			<xsd:element name="diagrama_hijo" type="xsd:string" minOccurs="0" maxOccurs="unbounded" />
			<xsd:element name="entidad" type="tipo_entidad" minOccurs="0" maxOccurs="unbounded" />
			<xsd:element name="relacion" type="tipo_relacion" minOccurs="0" maxOccurs="unbounded" />
			<xsd:element name="jerarquia" type="tipo_jerarquia" minOccurs="0" maxOccurs="unbounded" />
		</xsd:sequence>
		<xsd:attribute name="nombre" type="xsd:string" use="required" />
	</xsd:complexType>

	<xsd:complexType name="tipo_entidad">
		<xsd:sequence>
			<xsd:element name="atributo" type="tipo_atributo" minOccurs="1" maxOccurs="unbounded" />
			<xsd:element name="identificador" type="tipo_identificador" minOccurs="1" maxOccurs="unbounded" />
			<xsd:element name="relacion" type="xsd:string" minOccurs="0" maxOccurs="unbounded" /> 
			<xsd:element name="jerarquia" type="xsd:string" minOccurs="0" maxOccurs="unbounded" />
		</xsd:sequence>
		<xsd:attribute name="nombre" type="xsd:string" use="required" />
		<xsd:attribute name="tipo" type="xsd:string" />
	</xsd:complexType>

	<xsd:complexType name="tipo_relacion">
		<xsd:sequence>
			<xsd:element name="entidad" type="tipo_entidad_cardinalidad" minOccurs="2" maxOccurs="unbounded" />
			<xsd:element name="atributo" type="tipo_atributo" minOccurs="0" maxOccurs="unbounded" />
		</xsd:sequence>
		<xsd:attribute name="nombre" type="xsd:string" use="required" />
	</xsd:complexType>

	<xsd:complexType name="tipo_jerarquia">
		<xsd:sequence>
			<xsd:element name="entidad_padre" type="xsd:string" />
			<xsd:element name="entidad_hijo" type="xsd:string" maxOccurs="unbounded" />
		</xsd:sequence>
		<xsd:attribute name="nombre" type="xsd:string" use="required" />
		<xsd:attribute name="cardinalidad" type="xsd:string" use="required" />
	</xsd:complexType>

	<xsd:complexType name="tipo_atributo">
		<xsd:sequence>
			<xsd:element name="atributo_hijo" type="tipo_atributo" minOccurs="0" maxOccurs="unbounded" />
		</xsd:sequence>
		<xsd:attribute name="nombre" type="xsd:string" use="required" />
		<xsd:attribute name="tipo" type="tipo_tipo_atributo" use="required" /> 
		<xsd:attribute name="cardinalidad" type="xsd:string" />
	</xsd:complexType>

	<xsd:complexType name="tipo_identificador">
		<xsd:sequence>
			<xsd:element name="atributo" type="xsd:string" minOccurs="1" maxOccurs="unbounded" />
			<xsd:element name="relacion" type="xsd:string" minOccurs="0" maxOccurs="unbounded" /> 
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:simpleType name="tipo_tipo_atributo">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="integer" />
			<xsd:enumeration value="float" />
			<xsd:enumeration value="string" />
			<xsd:enumeration value="date" />
			<xsd:enumeration value="complex" />
		</xsd:restriction>
	</xsd:simpleType>
	
	<xsd:complexType name="tipo_entidad_cardinalidad">
		<xsd:attribute name="nombre" type="xsd:string" use="required" />
		<xsd:attribute name="cardinalidad" type="xsd:string" use="required" />
	</xsd:complexType>
	
</xsd:schema>

=== pablomagnaghi/7552-tp/trunk/TpTaller2V2/Prueba1-EjemploBoleteriaTeatro.xml
<?xml version="1.0" encoding="UTF-8"?>
<diagrama xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="composicion.xsd" nombre="boleteria teatro"><entidad_nueva codigo="1" nombre="SeccionSala" tipo="cosa"><atributo codigo="2" nombre="nroSecc" tipo="caracterizacion"/><atributo codigo="3" nombre="nomSecc" tipo="caracterizacion"/><identificador><atributo>2</atributo></identificador><identificador><atributo>3</atributo></identificador></entidad_nueva><entidad_nueva codigo="4" nombre="Localidad" tipo="cosa"><atributo codigo="5" nombre="fila" tipo="caracterizacion"/><atributo codigo="6" nombre="nroButaca" tipo="caracterizacion"/><identificador><atributo>5</atributo><atributo>6</atributo><relacion>18</relacion></identificador></entidad_nueva><entidad_nueva codigo="7" nombre="Obra" tipo="cosa"><atributo codigo="8" nombre="idObra" tipo="caracterizacion"/><atributo codigo="9" nombre="titulo" tipo="caracterizacion"/><atributo codigo="10" nombre="autor" tipo="caracterizacion" cardinalidad_minima="1" cardinalidad_maxima="n"/><atributo codigo="11" nombre="director" tipo="caracterizacion" cardinalidad_minima="1" cardinalidad_maxima="n"/><atributo codigo="12" nombre="genero" tipo="caracterizacion"/><atributo codigo="13" nombre="nroProxFunc" tipo="caracterizacion"/><identificador><atributo>8</atributo></identificador><identificador><atributo>9</atributo></identificador></entidad_nueva><entidad_nueva codigo="14" nombre="Funcion" tipo="cosa"><atributo codigo="15" nombre="nroFunc" tipo="caracterizacion"/><atributo codigo="16" nombre="fecha" tipo="caracterizacion"/><atributo codigo="17" nombre="hora" tipo="caracterizacion"/><identificador><atributo>15</atributo><relacion>32</relacion></identificador><identificador><atributo>16</atributo><atributo>17</atributo><relacion>32</relacion></identificador></entidad_nueva><relacion codigo="18" nombre="SL" tipo="asociacion"><union_entidad_relacion  codigo="19" entidad="1" cardinalidad_minima="1" cardinalidad_maxima="n"/><union_entidad_relacion  codigo="20" entidad="4" cardinalidad_minima="1" cardinalidad_maxima="1"/></relacion><relacion codigo="21" nombre="VtaLoc" tipo="asociacion"><union_entidad_relacion  codigo="22" entidad="4" cardinalidad_minima="0" cardinalidad_maxima="n"/><union_entidad_relacion  codigo="23" entidad="7" cardinalidad_minima="0" cardinalidad_maxima="n"/><atributo codigo="24" nombre="tarj" tipo="caracterizacion" cardinalidad_minima="0" cardinalidad_maxima="1"><atributo codigo="25" nombre="nomTarj" tipo="caracterizacion"/><atributo codigo="26" nombre="bco" tipo="caracterizacion"/><atributo codigo="27" nombre="nroTarj" tipo="caracterizacion"/><atributo codigo="28" nombre="nroAutoriz" tipo="caracterizacion"/><atributo codigo="29" nombre="cr" tipo="caracterizacion" cardinalidad_minima="0" cardinalidad_maxima="1"><atributo codigo="30" nombre="cuotas" tipo="caracterizacion"/><atributo codigo="31" nombre="int" tipo="calculado" expresion="cuotas*0.1" cardinalidad_minima="0" cardinalidad_maxima="1"/></atributo></atributo></relacion><relacion codigo="32" nombre="FO" tipo="asociacion"><union_entidad_relacion  codigo="33" entidad="7" cardinalidad_minima="0" cardinalidad_maxima="n"/><union_entidad_relacion  codigo="34" entidad="14" cardinalidad_minima="1" cardinalidad_maxima="1"/></relacion></diagrama>

=== pablomagnaghi/7552-tp/trunk/Tp Taller 2/Doc/XMLSchema/boleteria_teatro-comp.xml
<?xml version="1.0" encoding="UTF-8"?>
<diagrama xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:noNamespaceSchemaLocation="composicion.xsd"
	nombre="boleteria teatro">
		
	<entidad codigo="1" nombre="SeccionSala" >
		<atributo codigo="2" nombre="nroSecc" tipo="caracterizacion" composicion="simple"/>
		<atributo codigo="3" nombre="nomSecc" tipo="caracterizacion" composicion="simple"/>
		<identificador>
			<atributo>nroSecc</atributo>
		</identificador>
		<identificador>
			<atributo>nomSecc</atributo>
		</identificador>
		<relacion>SL</relacion>
	</entidad>
	
	<entidad codigo="4" nombre="Localidad">
		<atributo codigo="5" nombre="fila" tipo="caracterizacion" composicion="simple" />
		<atributo codigo="6" nombre="nroButaca" tipo="caracterizacion" composicion="simple" />
		<identificador>
			<atributo>fila</atributo>
			<atributo>nroButaca</atributo>
			<relacion>SL</relacion>
		</identificador>
		<relacion>SL</relacion>
		<relacion>VtaLoc</relacion>
	</entidad>
	
	<entidad codigo="7" nombre="Obra">
		<atributo codigo="8" nombre="idObra" tipo="caracterizacion" composicion="simple" />
		<atributo codigo="9" nombre="titulo" tipo="caracterizacion" composicion="simple" />
		<atributo codigo="10" nombre="autor" tipo="caracterizacion" composicion="simple" cardinalidad="(1,n)" />
		<atributo codigo="11" nombre="director" tipo="caracterizacion" composicion="simple" cardinalidad="(1,n)" />
		<atributo codigo="12" nombre="genero" tipo="caracterizacion" composicion="simple" />
		<atributo codigo="13" nombre="nroProxFunc" tipo="caracterizacion" composicion="simple" />
		<identificador>
			<atributo>idObra</atributo>
		</identificador>
		<identificador>
			<atributo>titulo</atributo>
		</identificador>  
		<relacion>VtaLoc</relacion>
		<relacion>FO</relacion>
	</entidad>
	
	<entidad codigo="14" nombre="Funcion">
		<atributo codigo="15" nombre="nroFunc" tipo="caracterizacion" composicion="simple" />
		<atributo codigo="16" nombre="fecha" tipo="caracterizacion" composicion="simple"/>
		<atributo codigo="17" nombre="hora" tipo="caracterizacion" composicion="simple"/>
		<identificador>
			<atributo>nroFunc</atributo>
			<relacion>FO</relacion>
		</identificador>
		<identificador>
			<atributo>fecha</atributo>
			<atributo>hora</atributo>
			<relacion>FO</relacion>
		</identificador>
		<relacion>FO</relacion> 
	</entidad>
	
	<relacion codigo="18" nombre="SL">
		<entidad nombre="SeccionSala" cardinalidad="(1,n)" />
		<entidad nombre="Localidad" cardinalidad="(1,1)" />
	</relacion>
	
	<relacion codigo="21" nombre="VtaLoc">
		<entidad nombre="Localidad" cardinalidad="(0,n)" />
		<entidad nombre="Obra" cardinalidad="(0,n)" />
		<atributo codigo="22" nombre="tarj" tipo="caracterizacion" composicion="compuesto" cardinalidad="(0,1)">
			<atributo_hijo codigo="23" nombre="nomTarj" tipo="caracterizacion" composicion="simple" />
			<atributo_hijo codigo="24" nombre="bco" tipo="caracterizacion" composicion="simple" />
			<atributo_hijo codigo="25" nombre="nroTarj" tipo="caracterizacion" composicion="simple" />
			<atributo_hijo codigo="26" nombre="nroAutoriz" tipo="caracterizacion" composicion="simple" />
			<atributo_hijo codigo="27" nombre="cr" tipo="caracterizacion" composicion="compuesto" cardinalidad="(0,1)">
				<atributo_hijo codigo="28" nombre="cuotas" tipo="caracterizacion" composicion="simple" />
				<atributo_hijo codigo="29" nombre="int" tipo="caracterizacion" cardinalidad="(0,1)" composicion="simple" />
			</atributo_hijo>
		</atributo>
	</relacion>
	
	<relacion codigo="30" nombre="FO">
		<entidad nombre="Obra" cardinalidad="(0,n)"/>
		<entidad nombre="Funcion" cardinalidad="(1,1)" />
	</relacion>
	
</diagrama>

=== pablomagnaghi/7552-tp/trunk/TpTaller2V2/proyectos/BoleteriaTeatro/Principal-COMP.xml
<?xml version="1.0" encoding="UTF-8"?>
<diagrama xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="composicion.xsd" nombre="Principal" estado="sin_validar"><entidad_nueva codigo="1" nombre="SeccionSala" tipo="cosa"><atributo codigo="2" nombre="nroSecc" tipo="Caracterizacion" cardinalidad_minima="1" cardinalidad_maxima="1"/><atributo codigo="4" nombre="nomSecc" tipo="Caracterizacion" cardinalidad_minima="1" cardinalidad_maxima="1"/><identificador><atributo>2</atributo></identificador><identificador><atributo>4</atributo></identificador></entidad_nueva><entidad_nueva codigo="6" nombre="Localidad" tipo="cosa"><atributo codigo="7" nombre="fila" tipo="Caracterizacion" cardinalidad_minima="1" cardinalidad_maxima="1"/><atributo codigo="9" nombre="nroButaca" tipo="Caracterizacion" cardinalidad_minima="1" cardinalidad_maxima="1"/><identificador><atributo>7</atributo><atributo>9</atributo></identificador><identificador><atributo>9</atributo><relacion>11</relacion></identificador></entidad_nueva><entidad_nueva codigo="14" nombre="Obra" tipo="cosa"><atributo codigo="15" nombre="idObra" tipo="Caracterizacion" cardinalidad_minima="1" cardinalidad_maxima="1"/><atributo codigo="17" nombre="titulo" tipo="Caracterizacion" cardinalidad_minima="1" cardinalidad_maxima="1"/><atributo codigo="19" nombre="autor" tipo="Caracterizacion" cardinalidad_minima="1" cardinalidad_maxima="n"/><atributo codigo="21" nombre="director" tipo="Caracterizacion" cardinalidad_minima="1" cardinalidad_maxima="n"/><atributo codigo="23" nombre="genero" tipo="Caracterizacion" cardinalidad_minima="1" cardinalidad_maxima="1"/><atributo codigo="25" nombre="Atributo" tipo="Caracterizacion" expresion="nroProxFuncion" cardinalidad_minima="1" cardinalidad_maxima="1"/><identificador><atributo>15</atributo></identificador><identificador><atributo>17</atributo></identificador></entidad_nueva><entidad_nueva codigo="27" nombre="Funcion" tipo="cosa"><atributo codigo="28" nombre="nroFunc" tipo="Caracterizacion" cardinalidad_minima="1" cardinalidad_maxima="1"/><atributo codigo="30" nombre="fecha" tipo="Caracterizacion" cardinalidad_minima="1" cardinalidad_maxima="1"/><atributo codigo="32" nombre="hora" tipo="Caracterizacion" cardinalidad_minima="1" cardinalidad_maxima="1"/><identificador><atributo>28</atributo><relacion>34</relacion></identificador><identificador><atributo>30</atributo><atributo>32</atributo><relacion>34</relacion></identificador></entidad_nueva><relacion codigo="11" nombre="SL" tipo="asociacion"><union_entidad_relacion  codigo="12" nombre="Union" entidad="1" cardinalidad_minima="1" cardinalidad_maxima="n"/><union_entidad_relacion  codigo="13" nombre="Union" entidad="6" cardinalidad_minima="1" cardinalidad_maxima=""/></relacion><relacion codigo="34" nombre="FO" tipo="asociacion"><union_entidad_relacion  codigo="35" nombre="Union" entidad="14" cardinalidad_minima="0" cardinalidad_maxima="n"/><union_entidad_relacion  codigo="36" nombre="Union" entidad="27" cardinalidad_minima="1" cardinalidad_maxima=""/></relacion><relacion codigo="37" nombre="VtaLoc" tipo="asociacion"><union_entidad_relacion  codigo="54" nombre="Union" entidad="6" cardinalidad_minima="" cardinalidad_maxima=""/><atributo codigo="38" nombre="tarj" tipo="Caracterizacion" cardinalidad_minima="0" cardinalidad_maxima="1"><atributo codigo="40" nombre="nomTarj" tipo="Caracterizacion" cardinalidad_minima="1" cardinalidad_maxima="1"/><atributo codigo="42" nombre="bco" tipo="Caracterizacion" cardinalidad_minima="1" cardinalidad_maxima="1"/><atributo codigo="44" nombre="nroTarj" tipo="Caracterizacion" cardinalidad_minima="1" cardinalidad_maxima="1"/><atributo codigo="46" nombre="nroAutoriz" tipo="Caracterizacion" cardinalidad_minima="1" cardinalidad_maxima="1"/><atributo codigo="48" nombre="cr" tipo="Caracterizacion" cardinalidad_minima="0" cardinalidad_maxima="1"><atributo codigo="50" nombre="cuotas" tipo="Caracterizacion" cardinalidad_minima="1" cardinalidad_maxima="1"/><atributo codigo="52" nombre="int" tipo="Caracterizacion" cardinalidad_minima="0" cardinalidad_maxima="1"/><atributo codigo="1" nombre="cuotas" tipo="Caracterizacion" cardinalidad_minima="0" cardinalidad_maxima="1"/><atributo codigo="3" nombre="int" tipo="Caracterizacion" cardinalidad_minima="0" cardinalidad_maxima="1"/></atributo></atributo></relacion></diagrama>
